# Environment Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
modId=pewpewcubes
modDisplayName=PewPewCubes
group=de.pewpewproject.pewpewcubes
modLicense=GPL-3.0
modAuthors=Etienne Muser, K e v, _Timon, ValliHalli
modContributors=Robert Senin, SolAstrum
modDescription=A mod to play lasertag in minecraft with your friends.
